### ISSUE TITLE
Add CI to run unit test

### ISSUE THREAD

**Issue by ikanago** [moisutsu/classopt#7]
This project does not seem to have any CI to verify which all tests have passes.
If we set up CI to run unit test, ✅(green check mark) is displayed for commits whose CI passes.
This ensures `classopt`'s behavior under current unit test, so users feels more reliable to use.

I have maintained [CI](https://github.com/Qulacs-Osaka/scikit-qulacs/tree/eb921f400e2c61fd308d04c2310bd3be4818c8c9/.github/workflows) to run unit test and other tasks for the project whose architecture is similar to `classopt`.
So I'd like to adjust GitHub Actions if you are OK.

**Comment by moisutsu** [comment]
Thanks for checking out this repository!!

I think it is important to maintain a CI as well. So I would like to ask @ikanago to maintain the CI.

**Comment by ikanago** [comment]
OK, I'll work on it!
